@baseURL = http://localhost:3000

### 1. Testar a rota POST /categorias (CREATE)
POST {{baseURL}}/categorias
Content-Type: application/json

{
  "nome": "Tecnologia",
  "descricao": "Categoria relacionada a Tecnologia."
}

### 2. Testar a rota GET /categorias (READ)
GET {{baseURL}}/categorias
Content-Type: application/json

### 3. Testar a rota PUT /categorias/:id (UPDATE)
PUT {{baseURL}}/categorias/1
Content-Type: application/json

{
  "nome": "Tecnologia Avançada",
  "descricao": "Categoria relacionada a Tecnologia Avançada."
}

### 4. Testar a rota DELETE /categorias/:id (DELETE)
DELETE {{baseURL}}/categorias/1
Content-Type: application/json
